### ISSUE TITLE
Not working (javascript)

### ISSUE THREAD

**Issue by barrosohub** [badboysm890/clara-copilot#5]
![image](https://user-images.githubusercontent.com/12834525/125176518-7cd5ac00-e1aa-11eb-96f9-04a989c90602.png)

**Comment by barrosohub** [comment]
![2021-07-10_18-13-47](https://user-images.githubusercontent.com/12834525/125176564-ba3a3980-e1aa-11eb-97d9-fa3e9a502fe1.gif)

**Comment by jwpjrdev** [comment]
This is happening because Grepper didn’t return any results. Currently, you have to specify a language in your query, but I’m working on a PR to clean up the code and add a few things. Among others are reformatting the code with Prettier and automatically appending the file’s set language’s name to your query (can be escaped with \ ofc) so you don’t have to write “rust” before your query every time you want to get something in rust.

I’ll clarify those additions more in the PR.

> On Jul 10, 2021, at 5:15 PM, Barroso Filho ***@***.***> wrote:
> 
> ﻿
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
________________________________________________


*CONFIDENTIALITY 
NOTICE:*

*The information transmitted in this electronic message may be 
legally privileged and confidential under applicable law, including the 
Family Educational Rights and Privacy Act (FERPA) and the Health Insurance 
Portability and Accountability Act (HIPAA), and is intended only for the 
person or entity to which it is addressed. If the recipient of this message 
is not the above named intended recipient, you are hereby notified that any 
review, retransmission, dissemination, copy, disclosure or other use of, or 
taking any action in reliance upon, this information by persons or entities 
other than the intended recipient is prohibited. If you received this 
electronic transmission in error, please notify Mississinewa Community 
School Corporation at (765) 674-8528, and purge the communication 
immediately from any computers, storage devices, paper or other media 
without making any copy or distribution thereof. Thank you for your 
cooperation.*

**Comment by jwpjrdev** [comment]
Grepper seems to be missing quite a few things so that's why you might get no results so often. It seems to be pretty good though.

**Comment by barrosohub** [comment]
This working:
javascript sort numbers
